// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColdShineSoft.PostEmulator.Models.Codes
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Java : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nURL url = new URL(\"");
            
            #line 7 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.Url));
            
            #line default
            #line hidden
            this.Write("\");\r\nHttpURLConnection httpURLConnection = (HttpURLConnection) url.openConnection" +
                    "();\r\nhttpURLConnection.setRequestMethod(\"");
            
            #line 9 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.HttpMethod.Method));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 10 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
 
foreach(RequestItem header in this.Task.HeaderItems.Where(h=>h.Selected))
{

            
            #line default
            #line hidden
            this.Write("httpURLConnection.setRequestProperty(\"");
            
            #line 14 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(header.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 14 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(header.Value));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 15 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 19 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"

if (this.Task.AcceptsRequestBody)
{

            
            #line default
            #line hidden
            this.Write("httpURLConnection.setDoOutput(true);\r\nDataOutputStream dataOutputStream = new Dat" +
                    "aOutputStream(httpURLConnection.getOutputStream());\r\ndataOutputStream.writeBytes" +
                    "(`");
            
            #line 25 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.PostStringContent));
            
            #line default
            #line hidden
            this.Write("`);\r\ndataOutputStream.flush();\r\ndataOutputStream.close();\r\n");
            
            #line 28 "G:\WindowsApplications\PostEmulator\Models\Codes\Java.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\nInputStream result=httpURLConnection.getInputStream();");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
