// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColdShineSoft.HttpClientPerformer.Models.Codes
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class JavaScript : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nconst axios = require(\'axios\');\r\nawait response=axios({\r\n\tmethod:\"");
            
            #line 9 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.HttpMethod.Method));
            
            #line default
            #line hidden
            this.Write("\",\r\n\turl:\"");
            
            #line 10 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.Url));
            
            #line default
            #line hidden
            this.Write("\",\r\n\theaders:{");
            
            #line 11 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",",this.Task.HeaderItems.Where(h => h.Selected).Select(h=>$"'{h.Name}':'{h.Value}'"))));
            
            #line default
            #line hidden
            this.Write("},\r\n");
            
            #line 12 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

if (this.Task.AcceptsRequestBody)
{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 16 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

	switch(this.Task.ContentType)
	{
		case RequestContentType.FormUrlencoded:
	
            
            #line default
            #line hidden
            this.Write("\tdata:{");
            
            #line 21 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",",this.Task.FormParameters.Where(p => p.Selected).Select(p=>$"'{p.Name}':'{p.Value}'"))));
            
            #line default
            #line hidden
            this.Write("}\r\n\t");
            
            #line 22 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

			break;
		case RequestContentType.Json:
	
            
            #line default
            #line hidden
            this.Write("\tdata:");
            
            #line 26 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.JsonContent));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 27 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

			break;
		default:
	
            
            #line default
            #line hidden
            this.Write("\tdata:`");
            
            #line 31 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Task.PostStringContent));
            
            #line default
            #line hidden
            this.Write("`\r\n\t");
            
            #line 32 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

			break;
	
            
            #line default
            #line hidden
            
            #line 35 "G:\WindowsApplications\HttpClientPerformer\Models\Codes\JavaScript.tt"

	}
}

            
            #line default
            #line hidden
            this.Write("});");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
